version: "3"
services:
   web-1:
      build: web/
      networks:
         - demonet-1
      ports:
         - "8080:8080"
      depends_on:
         - storage-1
   storage-1:
      build: storage/
      networks:
         - demonet-1
      ports:
         - "8081:8081"
      depends_on:
         - postgres-1
   postgres-1:
      image: postgres
      networks:
         - demonet-1
      environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=friend
networks:
   demonet-1: