apiVersion: v1
kind: Service
metadata:
  name: storage-1
spec:
  selector:
    app: storage
  ports:
    - port: 8081
      targetPort: 8081
#  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: feduk/storage
          ports:
            - containerPort: 8081
#          env:
#            - name: MONGO_URL
#              value: mongodb://mongo:27017/dev